# Generated by Django 6.0.6 on 2026-06-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'event')},
        ),
    ]
